// WCAG criterion extraction and description lookup for report enrichment.
// Derived from @luqen/core wcag-descriptions.ts to avoid a hard dependency.

export interface WcagCriterionInfo {
  readonly title: string;
  readonly description: string;
  readonly impact: string;
  readonly url: string;
}

/**
 * Extract a WCAG criterion number (e.g. "1.1.1") from a pa11y issue code.
 * Example: "WCAG2AA.Principle1.Guideline1_1.1_1_1.H37" -> "1.1.1"
 * Returns null if no criterion is found in the code.
 */
export function extractCriterion(pa11yCode: string): string | null {
  const match = pa11yCode.match(/(\d+)_(\d+)_(\d+)/);
  return match ? `${match[1]}.${match[2]}.${match[3]}` : null;
}

// Human-friendly descriptions for WCAG 2.1 Level A and AA success criteria.
const WCAG_DESCRIPTIONS: Record<string, WcagCriterionInfo> = {
  // Principle 1: Perceivable
  '1.1.1': { title: 'Non-text Content', description: 'All images, icons, and non-text content must have text alternatives that describe their purpose.', impact: 'Screen reader users cannot understand what images convey without alt text.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-content' },
  '1.2.1': { title: 'Audio-only and Video-only (Prerecorded)', description: 'Prerecorded audio-only and video-only content must have a text or audio alternative.', impact: 'Deaf, hard-of-hearing, or blind users cannot access media-only content.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-and-video-only-prerecorded' },
  '1.2.2': { title: 'Captions (Prerecorded)', description: 'Captions must be provided for all prerecorded audio content in synchronized media.', impact: 'Deaf and hard-of-hearing users cannot follow video dialogue without captions.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded' },
  '1.2.3': { title: 'Audio Description or Media Alternative (Prerecorded)', description: 'An audio description or text alternative must be provided for prerecorded video content.', impact: 'Blind users cannot perceive visual information in video without audio descriptions.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-or-media-alternative-prerecorded' },
  '1.2.4': { title: 'Captions (Live)', description: 'Captions must be provided for all live audio content in synchronized media.', impact: 'Deaf and hard-of-hearing users cannot follow live broadcasts without real-time captions.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/captions-live' },
  '1.2.5': { title: 'Audio Description (Prerecorded)', description: 'Audio description must be provided for all prerecorded video content.', impact: 'Blind users miss visual context in videos when audio descriptions are absent.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-prerecorded' },
  '1.3.1': { title: 'Info and Relationships', description: 'Information and relationships conveyed through presentation must also be available in code.', impact: 'Assistive technology users may miss the structure and meaning of content.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships' },
  '1.3.2': { title: 'Meaningful Sequence', description: 'When the order of content matters, the correct reading sequence must be determinable programmatically.', impact: 'Screen reader users encounter content out of order, leading to confusion.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence' },
  '1.3.3': { title: 'Sensory Characteristics', description: 'Instructions must not rely solely on shape, color, size, visual location, orientation, or sound.', impact: 'Users who are blind or color-blind cannot follow instructions tied to visual appearance alone.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics' },
  '1.3.4': { title: 'Orientation', description: 'Content must not restrict its view and operation to a single display orientation unless essential.', impact: 'Users who mount devices in a fixed orientation cannot use restricted content.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/orientation' },
  '1.3.5': { title: 'Identify Input Purpose', description: 'The purpose of each input field collecting information about the user must be programmatically determinable.', impact: 'Users with cognitive disabilities cannot benefit from autofill when input purpose is not identified.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose' },
  '1.4.1': { title: 'Use of Color', description: 'Color must not be used as the only visual means of conveying information.', impact: 'Color-blind users cannot distinguish information conveyed by color alone.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/use-of-color' },
  '1.4.2': { title: 'Audio Control', description: 'If audio plays automatically for more than 3 seconds, a mechanism must be provided to pause, stop, or control the volume.', impact: 'Screen reader users cannot hear their assistive technology when audio plays over it.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-control' },
  '1.4.3': { title: 'Contrast (Minimum)', description: 'Text must have a contrast ratio of at least 4.5:1 against its background (3:1 for large text).', impact: 'Users with low vision or color blindness cannot read text with insufficient contrast.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum' },
  '1.4.4': { title: 'Resize Text', description: 'Text must be resizable up to 200% without loss of content or functionality.', impact: 'Users with low vision who increase text size may lose access to content if the page breaks.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/resize-text' },
  '1.4.5': { title: 'Images of Text', description: 'Images of text should only be used when a particular presentation is essential; real text is preferred.', impact: 'Images of text cannot be resized, recolored, or read reliably by assistive technologies.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/images-of-text' },
  '1.4.10': { title: 'Reflow', description: 'Content must reflow into a single column at 320 CSS pixels wide without loss of information or requiring horizontal scrolling.', impact: 'Users with low vision who zoom into pages lose access to content requiring horizontal scrolling.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/reflow' },
  '1.4.11': { title: 'Non-text Contrast', description: 'UI components and graphical objects must have at least a 3:1 contrast ratio against adjacent colors.', impact: 'Users with low vision cannot see interface controls or meaningful graphics with insufficient contrast.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast' },
  '1.4.12': { title: 'Text Spacing', description: 'Content must remain readable when users override line height, letter spacing, word spacing, and paragraph spacing.', impact: 'Users with dyslexia who adjust text spacing may encounter content that breaks or overlaps.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/text-spacing' },
  '1.4.13': { title: 'Content on Hover or Focus', description: 'Content that appears on hover or focus must be dismissible, hoverable, and persistent.', impact: 'Users with low vision and motor disabilities cannot access or dismiss tooltip-style content.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus' },
  // Principle 2: Operable
  '2.1.1': { title: 'Keyboard', description: 'All functionality must be operable via a keyboard without requiring specific timing.', impact: 'Users who cannot use a mouse rely entirely on keyboard access; missing keyboard support excludes them.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/keyboard' },
  '2.1.2': { title: 'No Keyboard Trap', description: 'Keyboard focus must not become trapped; users must be able to move focus away from any component.', impact: 'Keyboard users get stuck in a component and cannot navigate the rest of the page.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/no-keyboard-trap' },
  '2.1.4': { title: 'Character Key Shortcuts', description: 'If single-character key shortcuts exist, users must be able to turn them off, remap, or activate only on focus.', impact: 'Users who speak commands or have motor disabilities may accidentally trigger shortcuts.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts' },
  '2.2.1': { title: 'Timing Adjustable', description: 'Time limits must be adjustable: users can turn off, extend, or adjust any time limit unless essential.', impact: 'Users who need more time may be timed out before completing tasks.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable' },
  '2.2.2': { title: 'Pause, Stop, Hide', description: 'Moving, blinking, or scrolling content that starts automatically must have a mechanism to pause, stop, or hide it.', impact: 'Users with attention or cognitive disabilities are distracted by moving content they cannot stop.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide' },
  '2.3.1': { title: 'Three Flashes or Below Threshold', description: 'Pages must not contain content that flashes more than three times per second.', impact: 'Content that flashes rapidly can trigger seizures in users with photosensitive epilepsy.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold' },
  '2.4.1': { title: 'Bypass Blocks', description: 'A mechanism must be provided to skip repeated blocks of content.', impact: 'Keyboard users must tab through every navigation link on every page without a skip link.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks' },
  '2.4.2': { title: 'Page Titled', description: 'Web pages must have descriptive, meaningful titles.', impact: 'Users navigating with browser tabs or screen readers cannot identify pages without titles.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/page-titled' },
  '2.4.3': { title: 'Focus Order', description: 'Focusable components must receive focus in an order that preserves meaning and operability.', impact: 'Keyboard and screen reader users are confused when focus jumps around in an illogical order.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-order' },
  '2.4.4': { title: 'Link Purpose (In Context)', description: 'The purpose of each link must be clear from the link text alone, or from the link text together with its context.', impact: 'Screen reader users navigating a list of links cannot determine where vague links go.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context' },
  '2.4.5': { title: 'Multiple Ways', description: 'More than one way must be provided to locate a page within a set of pages.', impact: 'Users who cannot use certain navigation mechanisms are blocked from finding content.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways' },
  '2.4.6': { title: 'Headings and Labels', description: 'Headings and labels must describe the topic or purpose of the associated content.', impact: 'Screen reader users rely on headings to scan and navigate; vague headings make orientation impossible.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels' },
  '2.4.7': { title: 'Focus Visible', description: 'Any keyboard-operable interface must have a visible focus indicator.', impact: 'Keyboard users cannot tell which element has focus when the indicator is invisible.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-visible' },
  '2.5.1': { title: 'Pointer Gestures', description: 'All functionality that uses multipoint or path-based gestures must be operable with a single pointer.', impact: 'Users with motor disabilities who cannot perform complex gestures lose access.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures' },
  '2.5.2': { title: 'Pointer Cancellation', description: 'Functions triggered by a single pointer must be cancellable or reversible to prevent accidental activation.', impact: 'Users with tremors who accidentally touch a target cannot undo unintended actions.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation' },
  '2.5.3': { title: 'Label in Name', description: 'For UI components with visible text labels, the accessible name must contain the visible text.', impact: 'Voice control users who speak the visible label cannot activate controls with mismatched accessible names.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/label-in-name' },
  '2.5.4': { title: 'Motion Actuation', description: 'Functionality triggered by device motion must also be operable through UI components.', impact: 'Users with tremors or who mount devices in fixed positions cannot use motion-triggered features.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation' },
  // Principle 3: Understandable
  '3.1.1': { title: 'Language of Page', description: 'The default human language of each page must be programmatically determinable.', impact: 'Screen readers may mispronounce content if the page language is not declared in the HTML.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-page' },
  '3.1.2': { title: 'Language of Parts', description: 'The language of each passage or phrase in the content must be programmatically determinable.', impact: 'Screen readers cannot switch pronunciation correctly between languages when parts are not marked up.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts' },
  '3.2.1': { title: 'On Focus', description: 'Receiving keyboard focus must not trigger an unexpected change of context.', impact: 'Keyboard and screen reader users are disoriented when focusing an element causes page changes.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/on-focus' },
  '3.2.2': { title: 'On Input', description: 'Changing a form control must not automatically cause a change of context without warning the user.', impact: 'Users with motor impairments may accidentally trigger navigation or actions.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/on-input' },
  '3.2.3': { title: 'Consistent Navigation', description: 'Navigation mechanisms repeated across pages must occur in the same relative order each time.', impact: 'Users with cognitive disabilities are confused when navigation moves around between pages.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation' },
  '3.2.4': { title: 'Consistent Identification', description: 'Components with the same functionality must be identified consistently across the website.', impact: 'Users who learn one component cannot transfer that knowledge when identical components are labeled differently.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification' },
  '3.3.1': { title: 'Error Identification', description: 'If an input error is detected automatically, the item in error must be identified and described in text.', impact: 'Users who are blind or have cognitive disabilities cannot identify and correct errors from visual cues alone.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/error-identification' },
  '3.3.2': { title: 'Labels or Instructions', description: 'Labels or instructions must be provided when content requires user input.', impact: 'Users do not know what is expected in a form field without labels or instructions.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions' },
  '3.3.3': { title: 'Error Suggestion', description: 'If an input error is detected and suggestions for correction are known, the suggestion must be provided.', impact: 'Users who make mistakes have no guidance on how to correct them.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion' },
  '3.3.4': { title: 'Error Prevention (Legal, Financial, Data)', description: 'For legal, financial, or data-deletion submissions, users must be able to review, correct, and confirm or reverse their submission.', impact: 'Users with cognitive or motor disabilities may make unintentional errors with serious consequences.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-legal-financial-data' },
  // Principle 4: Robust
  '4.1.1': { title: 'Parsing', description: 'HTML must have complete start and end tags, not duplicate attributes, and properly nested elements.', impact: 'Malformed HTML may be interpreted differently across browsers and assistive technologies.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/parsing' },
  '4.1.2': { title: 'Name, Role, Value', description: 'All UI components must have programmatically determinable names, roles, states, and values.', impact: 'Screen reader users cannot interact with unlabeled or incorrectly coded controls.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/name-role-value' },
  '4.1.3': { title: 'Status Messages', description: 'Status messages must be programmatically determinable so they can be announced by assistive technology without receiving focus.', impact: 'Screen reader users do not hear status updates that appear dynamically.', url: 'https://www.w3.org/WAI/WCAG21/Understanding/status-messages' },
};

/**
 * Retrieve plain-language information for a WCAG success criterion number.
 * Returns null if the criterion is not in the map.
 */
export function getWcagDescription(criterion: string): WcagCriterionInfo | null {
  return WCAG_DESCRIPTIONS[criterion] ?? null;
}
