apiVersion: v1
kind: Service
metadata:
  name: pally-compliance
  namespace: pally
  labels:
    app.kubernetes.io/name: pally-compliance
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: pally-ecosystem
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pally-compliance
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
